blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: https://gitlab.com/Oslandia/test_templater_github/
    about: Please read carefully the documentation before to submit an issue.
